name=input("enter the name")
dob=input("enter the date of birth")
email=input("enter the email id")
phone=input("enter the phone number")
pin=input("enter the pin code")
user=input("enter the user name")
password=input("enter the password")
password1=input("confirm the password")
print(name)
print(dob)
print(email)
print(phone)
print(pin)
print(user)
print(password)
print(password1)
